AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Handler: index.handler
    Runtime: nodejs20.x
    Timeout: 300
    MemorySize: 1024

Mappings:
  RegionMap:
    us-east-1:
      RegionShortName: ''
    us-west-1:
      RegionShortName: 'uw1'
    us-east-2:
      RegionShortName: 'ue2'

Resources:
  ContactDynamoDBJulianParra:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: contact-julianparra
      AttributeDefinitions:
        - AttributeName: "email"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "email"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      Tags:
        - Key: "SYSTEM"
          Value: work-shop-julianparra

  ContactApiJulianParra:
    Type: AWS::Serverless::Api
    Properties:
      Name: contact-api-julianparra
      EndpointConfiguration: REGIONAL
      StageName: prod
      Cors:
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent,id-token'"
        AllowMethods: "'DELETE,GET,OPTIONS,POST,PUT'"
        AllowOrigin: "'*'"

  ContactCreateLambdaJulianParra:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: contact-create-julianparra
      CodeUri: build/create
      Role: !GetAtt ContactCreateRoleJulianParra.Arn
      Environment:
        Variables:
          TABLE_NAME_CONTACTS: !Ref ContactDynamoDBJulianParra
      Tags:
        SYSTEM: 'work-shop-julianparra'
      Events:
        CreateRequest:
          Type: Api
          Properties:
            RestApiId: !Ref ContactApiJulianParra
            Path: /
            Method: POST

  ContactCreateRoleJulianParra:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub
        - 'ContactCreateRoleJulianParra${region}'
        - region: !FindInMap [RegionMap, !Ref 'AWS::Region', RegionShortName]
      Description: Create contact role Julian Parra
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
      Policies:
        - PolicyName: DynamoDBPolicyJulianParra
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                Resource: !GetAtt ContactDynamoDBJulianParra.Arn

  ContactCreateLogGroupJulianParra:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub
        - /aws/lambda/${MyLambdaFunction}
        - MyLambdaFunction: !Ref ContactCreateLambdaJulianParra
      RetentionInDays: 7

  ContactDeleteLambdaJulianParra:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: contact-delete-julianparra
      CodeUri: build/delete
      Role: !GetAtt ContactDeleteRoleJulianParra.Arn
      Environment:
        Variables:
          TABLE_NAME_CONTACTS: !Ref ContactDynamoDBJulianParra
      Tags:
        SYSTEM: 'work-shop-julianparra'
      Events:
        DeleteRequest:
          Type: Api
          Properties:
            RestApiId: !Ref ContactApiJulianParra
            Path: /{email}
            Method: DELETE

  ContactDeleteRoleJulianParra:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub
        - 'ContactDeleteRoleJulianParra${region}'
        - region: !FindInMap [RegionMap, !Ref 'AWS::Region', RegionShortName]
      Description: Delete contact role Julian Parra
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
      Policies:
        - PolicyName: DynamoDBPolicyJulianParra
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:DeleteItem
                Resource: !GetAtt ContactDynamoDBJulianParra.Arn

  ContactDeleteLogGroupJulianParra:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub
        - /aws/lambda/${MyLambdaFunction}
        - MyLambdaFunction: !Ref ContactDeleteLambdaJulianParra
      RetentionInDays: 7

  ContactGetLambdaJulianParra:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: contact-get-julianparra
      CodeUri: build/get
      Role: !GetAtt ContactGetRoleJulianParra.Arn
      Environment:
        Variables:
          TABLE_NAME_CONTACTS: !Ref ContactDynamoDBJulianParra
      Tags:
        SYSTEM: 'work-shop-julianparra'
      Events:
        GetRequest:
          Type: Api
          Properties:
            RestApiId: !Ref ContactApiJulianParra
            Path: /{email}
            Method: GET

  ContactGetRoleJulianParra:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub
        - 'ContactGetRoleJulianParra${region}'
        - region: !FindInMap [RegionMap, !Ref 'AWS::Region', RegionShortName]
      Description: Get contact role Julian Parra
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
      Policies:
        - PolicyName: DynamoDBPolicyJulianParra
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                Resource: !GetAtt ContactDynamoDBJulianParra.Arn

  ContactGetLogGroupJulianParra:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub
        - /aws/lambda/${MyLambdaFunction}
        - MyLambdaFunction: !Ref ContactGetLambdaJulianParra
      RetentionInDays: 7

  ContactUpdateLambdaJulianParra:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: contact-update-julianparra
      CodeUri: build/update
      Role: !GetAtt ContactUpdateRoleJulianParra.Arn
      Environment:
        Variables:
          TABLE_NAME_CONTACTS: !Ref ContactDynamoDBJulianParra
      Tags:
        SYSTEM: 'work-shop-julianparra'
      Events:
        PutRequest:
          Type: Api
          Properties:
            RestApiId: !Ref ContactApiJulianParra
            Path: /{email}
            Method: PUT

  ContactUpdateRoleJulianParra:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub
        - 'ContactUpdateRoleJulianParra${region}'
        - region: !FindInMap [RegionMap, !Ref 'AWS::Region', RegionShortName]
      Description: Update contact role Julian Parra
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
      Policies:
        - PolicyName: DynamoDBPolicyJulianParra
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                Resource: !GetAtt ContactDynamoDBJulianParra.Arn

  ContactUpdateLogGroupJulianParra:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub
        - /aws/lambda/${MyLambdaFunction}
        - MyLambdaFunction: !Ref ContactUpdateLambdaJulianParra
      RetentionInDays: 7